version: '3.9'
services:
  graphql_server:
    build: .
    volumes:
      - .:/home/app
    ports:
      - 4000:4000
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    volumes:
      - ${DB_FOLDER}:/var/lib/postgresql/data
    ports:
      - 5432:5432
