FROM node:20-slim
WORKDIR /home/node/app

# COPY package*.json .
# COPY . .
# RUN ["npm",  "ci"]

# USER node
# RUN apt-get update && apt-get install -y libssl1.1
RUN apt-get update && apt-get install -y openssl
CMD ["tail", "-f", "/dev/null"]

