FROM node:22-slim

RUN apt-get update -y && apt-get install -y openssl procps \
    && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@latest --activate

# Match container "node" user/group IDs with host "apps" user (1003:1003)
RUN usermod -u 1003 node \
    && groupmod -g 1003 node

WORKDIR /home/node/app

RUN chown -R node:node /home/node/app
RUN mkdir -p /home/node/logs && chown -R node:node /home/node/logs

USER node

CMD ["tail", "-f", "/dev/null"]
