services:
  graphql_server_dev:
    container_name: graphql_server_dev
    image: graphql_server_dev
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "npm run start:dev"
    volumes:
      - /home/apps/emater_graphql_server:/home/node/app
      - /home/apps/emater_graphql_server/logs/dev:/home/node/logs
    ports:
      - 4000:4000
    networks:
      - emater_gql_dev

networks:
  emater_gql_dev:
    name: emater_gql_dev

