version: '3.9'
services:
  graphql_server:
    container_name: graphql_server
    build:
      context: ${HOME_FOLDER}
      dockerfile: Dockerfile.prod
    image: graphql_server
    command: "sh -c 'npm run start:prod || sleep infinity'"
    # volumes:
    #   - ${HOME_FOLDER}:/home/node/app
    ports:
      - 4000:4000
  # entrypoint: "dockerize -wait tcp://postgres:5432 -timeout 20s /usr/local/bin/docker-entrypoint.sh"
  #   depends_on:
  #     - postgres
  # postgres:
  #   image: postgres:15
  #   volumes:
  #     - ${DB_FOLDER}:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
