FROM node:22-slim

RUN apt-get update -y && apt-get install -y openssl procps \
    && usermod -u 1000 node \
    && groupmod -g 1000 node \
    && groupadd -g 1003 apps \
    && usermod -aG 1003 node

WORKDIR /home/node/app

# RUN apt-get update && apt-get install -y openssl

# RUN chown -R node:node /home/node/app
# RUN usermod -u 1001 node && groupmod -g 1001 node

CMD ["tail", "-f", "/dev/null"]

