FROM node:22-slim
WORKDIR /home/node/app

RUN apt-get update && apt-get install -y openssl

RUN chown -R node:node /home/node/app
RUN usermod -u 1001 node && groupmod -g 1001 node

CMD ["tail", "-f", "/dev/null"]

