services:
  graphql_server_prod:
    image: graphql_server_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    command: "npm run start:prod"
    env_file:
      - production.env
    environment:
      - NODE_ENV=production
    volumes:
      - /home/apps/emater_graphql_server/logs/prod:/home/node/logs
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 2048M
    networks:
      - pnae_prod_default
      - cmc_prod

networks:
  pnae_prod_default:
    external: true
  cmc_prod:
    external: true
