services:
  graphql_server_hmg:
    container_name: graphql_server_hmg
    image: graphql_server_hmg
    build:
      context: .
      dockerfile: Dockerfile.hmg
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    command: "npm run start:prod"
    environment:
      - NODE_ENV=production
    ports:
      - 4100:4100
    networks:
      - pnae_hmg_default
      - cmc_hmg

networks:
  pnae_hmg_default:
    external: true
  cmc_hmg:
    external: true
